/*
 * The contents of this file are subject to the terms
 * of the Common Development and Distribution License
 * (the "License").  You may not use this file except
 * in compliance with the License.
 * 
 * You can obtain a copy of the license at
 * http://www.opensource.org/licenses/cddl1.php
 * See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*
 * ResourceConfig.java
 *
 * Created on January 31, 2007, 4:43 PM
 *
 */

package javax.ws.rs.core;

import java.util.Set;

/**
 * Methods describing the set of resources in a Web application. It is anticipated
 * that an implementation of this interface will be generated by tools rather
 * than directly implemented by developers.
 */
public interface ResourceConfig {
    /**
     * Get the set of resource classes that should be deployed. A resource class
     * is a class with a <code>UriTemplate</code> annotation.
     * @return the set of resource classes.
     */
    Set<Class> getResourceClasses();

    /**
     * Specifies whether matrix parameters are ignored for the purposes
     * of matching a request URI to a resource class.
     * @return true if matrix params should be ignored, false if not
     */
    boolean isIgnoreMatrixParams();

    /**
     * Specifies whether the runtime should silently normalize the request URI
     * or issue a client redirect to the normailzed request URI.
     * @return true if redirects will be used, false if not
     */
    boolean isRedirectToNormalizedURI();
}
